# Generated by Django 6.1.1 on 2026-09-29 11:09

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.jobs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0006_field_service_contacts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pricing_unit",
                    models.CharField(
                        choices=[
                            ("flat", "Flat rate"),
                            ("hour", "Per hour"),
                            ("window", "Per window"),
                            ("linear_ft", "Per linear foot"),
                            ("sq_ft", "Per square foot"),
                            ("item", "Per item"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "followup_interval_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Suggest a follow-up this many months after the last job. Leave blank to never auto-generate follow-ups for this service.",
                        null=True,
                    ),
                ),
                (
                    "tone",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Calendar color (1-10).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "customer_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="crm.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_rep",
                    models.ForeignKey(
                        blank=True,
                        help_text="Credited with this job's revenue.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="crm.property",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_start", "pk"],
            },
            bases=(apps.jobs.models.TotalMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("issued_on", models.DateField(db_index=True)),
                ("due_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent"), ("void", "Void")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="crm.contact",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-pk"],
            },
            bases=(apps.jobs.models.TotalMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JobAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="crew",
            field=models.ManyToManyField(
                related_name="crew_jobs", through="jobs.JobAssignment", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("received_on", models.DateField(db_index=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("card", "Card"),
                            ("transfer", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        default="card",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="jobs.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "site_visit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Estimate appointment — shown on the calendar.",
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_deal_id",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="crm.contact",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="crm.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
            bases=(apps.jobs.models.TotalMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("before", "Before"),
                            ("after", "After"),
                            ("reference", "Reference"),
                        ],
                        default="reference",
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to=apps.jobs.models.photo_upload_to)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="jobs.job",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="jobs.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.quote",
            ),
        ),
        migrations.CreateModel(
            name="QuoteLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="jobs.quote",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="jobs.servicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="jobs.job",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="jobs.servicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="job",
            name="primary_service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_jobs",
                to="jobs.servicetype",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="jobs.invoice",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="jobs.servicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplies", "Supplies & chemicals"),
                            ("fuel", "Fuel & vehicle"),
                            ("equipment", "Equipment"),
                            ("payroll", "Payroll"),
                            ("insurance", "Insurance"),
                            ("marketing", "Marketing"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_on__gte", models.F("issued_on"))),
                name="invoice_due_on_or_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobassignment",
            constraint=models.UniqueConstraint(
                fields=("job", "user"), name="one_assignment_per_crew_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hours_worked__isnull", True), ("hours_worked__gte", 0), _connector="OR"
                ),
                name="assignment_hours_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["site_visit_at"], name="jobs_quote_site_vi_3df19d_idx"),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("job__isnull", False), ("quote__isnull", True)),
                    models.Q(("job__isnull", True), ("quote__isnull", False)),
                    _connector="OR",
                ),
                name="photo_belongs_to_exactly_one_job_or_quote",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="quote_line_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="quote_line_unit_price_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="job_line_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="joblineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="job_line_unit_price_not_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["scheduled_start"], name="jobs_job_schedul_4e512d_idx"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_end__gt", models.F("scheduled_start"))),
                name="job_ends_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("customer_rating__isnull", True),
                    models.Q(("customer_rating__gte", 1), ("customer_rating__lte", 5)),
                    _connector="OR",
                ),
                name="job_rating_between_1_and_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="invoice_line_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="invoice_line_unit_price_not_negative",
            ),
        ),
    ]
