# Generated by Django 6.1.1 on 2026-10-05 02:29

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("google", "Google Business Profile"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("yelp", "Yelp"),
                            ("nextdoor", "Nextdoor"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Required for Other links.", max_length=60
                    ),
                ),
                ("url", models.URLField(max_length=300, verbose_name="Link")),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("platform", "other"), _negated=True),
                        fields=("platform",),
                        name="one_link_per_main_platform",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("platform", "other"), _negated=True),
                            models.Q(("label", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="other_link_has_label",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if you're operating as a freelancer",
                        max_length=120,
                        verbose_name="Business name",
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to=apps.core.models.logo_upload_to)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US dollar ($)"), ("CAD", "Canadian dollar (CA$)")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "business settings",
                "verbose_name_plural": "business settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="single_business_settings_row"
                    )
                ],
            },
        ),
    ]
