# Generated by Django 6.1.1 on 2026-10-05 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_business_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue invoiced"),
                            ("jobs", "Jobs completed"),
                            ("customers", "New customers"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["metric"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("follow_up", "Follow-up"),
                            ("job", "Job"),
                            ("estimate", "Estimate"),
                            ("invoice", "Invoice"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(blank=True, max_length=300)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^/", "Must be a path on this site."
                            )
                        ],
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(fields=["recipient", "read_at"], name="notification_inbox_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("event", ""), _negated=True),
                        fields=("recipient", "event"),
                        name="one_notification_per_event",
                    )
                ],
            },
        ),
    ]
