# Generated by Django 6.1.1 on 2026-09-29 11:09

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to=apps.users.models.avatar_upload_to),
        ),
    ]
