# Generated by Django 6.1.1 on 2026-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_field_service_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("system", "Match my device"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                max_length=10,
            ),
        ),
    ]
