# Generated by Django 6.1.1 on 2026-10-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_dismissed",
            field=models.BooleanField(default=False),
        ),
    ]
