# Generated by Django 6.1.1 on 2026-10-05 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userprofile_onboarding_dismissed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What this person is paid per hour. Payroll needs it.",
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="working_days",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
