# Generated by Django 6.1.1 on 2026-09-11 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("probability__isnull", True),
                    models.Q(("probability__gte", 0), ("probability__lte", 100)),
                    _connector="OR",
                ),
                name="deal_probability_between_0_and_100",
            ),
        ),
    ]
