# Generated by Django 6.1.1 on 2026-09-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_deal_deal_probability_between_0_and_100"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activity",
            name="activity_has_related_object",
        ),
        migrations.AlterField(
            model_name="activity",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.company",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.contact",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.deal",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.lead",
            ),
        ),
    ]
