# Generated by Django 6.1.1 on 2026-09-29 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_field_service_contacts"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[("general", "General"), ("follow_up", "Follow-up")],
                db_index=True,
                default="general",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="jobs.quote",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="jobs.servicetype",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("meeting", "Meeting"),
                    ("email", "Email"),
                    ("note", "Note"),
                    ("text", "Text message"),
                    ("visit", "Site visit"),
                    ("follow_up", "Follow-up"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "follow_up"), _negated=True),
                    models.Q(("contact__isnull", False), ("service_type__isnull", False)),
                    _connector="OR",
                ),
                name="follow_up_has_contact_and_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "follow_up"), ("status", "pending")),
                fields=("contact", "service_type"),
                name="one_open_follow_up_per_contact_service",
            ),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_business_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_set",
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_set",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="planchecklistitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="crm.businessplan",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="contacts", to="crm.tag"),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("contact",),
                name="one_primary_property_per_contact",
            ),
        ),
    ]
