# Generated by Django 6.1.1 on 2026-10-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_property_latitude_property_located_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="located_address",
            field=models.CharField(blank=True, editable=False, max_length=450),
        ),
    ]
