# Generated by Django 6.1.1 on 2026-10-09 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crm", "0009_alter_property_located_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(fields=["-created_at"], name="crm_audit_recent_idx"),
        ),
    ]
